apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opensearchclusters.opensearch.reclaim-the-stack.com
spec:
  group: opensearch.reclaim-the-stack.com
  names:
    kind: OpenSearchCluster
    plural: opensearchclusters
    singular: opensearchcluster
    shortNames: [osc]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [diskSize]
              properties:
                image:
                  type: string
                  description: OpenSearch image (e.g., opensearchproject/opensearch:<tag>)
                  default: opensearchproject/opensearch:3.2.0
                replicas:
                  type: integer
                  minimum: 1
                  default: 1
                diskSize:
                  type: string
                resources:
                  type: object
                  description: Pod resources (limits/requests)
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                tolerations:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      value:
                        type: string
                      effect:
                        type: string
            status:
              type: object
              properties:
                health:
                  type: string
                nodes:
                  type: integer
                version:
                  type: string
                phase:
                  type: string
