apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opensearches.opensearch.reclaim-the-stack.com
spec:
  group: opensearch.reclaim-the-stack.com
  names:
    kind: OpenSearch
    plural: opensearches
    singular: opensearch
    shortNames: [os]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .status.version
        - name: Health
          type: string
          jsonPath: .status.health
        - name: Nodes
          type: integer
          jsonPath: .status.nodes
        - name: Phase
          type: string
          jsonPath: .status.phase
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [image, replicas, diskSize, resources, snapshotRepositories]
              properties:
                image:
                  type: string
                  description: OpenSearch image (e.g., opensearchproject/opensearch:<major>.<minor>.<patch>)
                  default: opensearchproject/opensearch:3.3.0
                  pattern: :[0-9]+\.[0-9]+\.[0-9]+$ # validate that the tag is in semver format
                replicas:
                  type: integer
                  minimum: 3
                  default: 3
                diskSize:
                  type: string
                resources:
                  description: |-
                    Regular Kubernetes resource requests and limits for OpenSearch nodes.
                  type: object
                  required:
                    - limits
                    - requests
                  properties:
                    limits:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      required:
                        - memory
                      properties:
                        memory:
                          type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                      x-kubernetes-validations:
                        - message: spec.resources.limits.memory must be at least 4Gi
                          rule: quantity(self.memory).compareTo(quantity('4Gi')) >= 0
                    requests:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      required:
                        - memory
                      properties:
                        memory:
                          type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                      x-kubernetes-validations:
                        - message: spec.resources.requests.memory must be at least 4Gi
                          rule: quantity(self.memory).compareTo(quantity('4Gi')) >= 0
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                tolerations:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      value:
                        type: string
                      effect:
                        type: string
                snapshotRepositories:
                  type: array
                  description: List of snapshot repositories that should be created in the OpenSearch cluster.
                  default: []
                  items:
                    type: object
                    required:
                      - name
                      - type
                      - bucket
                      - accessKeyId
                      - secretAccessKey
                      - policies
                    properties:
                      name:
                        type: string
                        description: Repository identifier used inside OpenSearch.
                      type:
                        type: string
                        description: Backend type for the repository.
                        enum:
                          - s3
                        default: s3
                      bucket:
                        type: string
                        description: S3 bucket that stores the snapshots.
                      base_path:
                        type: string
                        description: Path prefix within the bucket.
                      endpoint:
                        type: string
                        description: Optional custom S3-compatible endpoint.
                      protocol:
                        type: string
                        description: Protocol used to connect to the endpoint.
                        enum:
                          - http
                          - https
                        default: https
                      region:
                        type: string
                        description: AWS region for the bucket.
                      accessKeyId:
                        type: object
                        description: Secret reference containing the AWS access key id.
                        required:
                          - name
                          - key
                        properties:
                          name:
                            type: string
                            description: Name of the Kubernetes Secret holding the value.
                          key:
                            type: string
                            description: Key in the Kubernetes Secret that stores the value.
                      secretAccessKey:
                        type: object
                        description: Secret reference containing the AWS secret access key.
                        required:
                          - name
                          - key
                        properties:
                          name:
                            type: string
                            description: Name of the Kubernetes Secret holding the value.
                          key:
                            type: string
                            description: Key in the Kubernetes Secret that stores the value.
                      policies:
                        type: array
                        description: Snapshot Management policies that should be created for this repository.
                        default: []
                        items:
                          type: object
                          required:
                            - name
                            - schedule
                            - max_age
                          properties:
                            name:
                              type: string
                              description: Short identifier appended to the repository name when creating the policy.
                            schedule:
                              type: string
                              description: Cron expression defining when snapshots should be taken (UTC timezone).
                            max_age:
                              type: string
                              description: Retention period after which snapshots created by this policy are deleted (e.g., 30d).
            status:
              type: object
              properties:
                health:
                  type: string
                nodes:
                  type: integer
                version:
                  type: string
                phase:
                  type: string
