apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opensearchclusters.opensearch.reclaim-the-stack.com
spec:
  group: opensearch.reclaim-the-stack.com
  names:
    kind: OpenSearchCluster
    plural: opensearchclusters
    singular: opensearchcluster
    shortNames: [osc]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Version
          type: string
          jsonPath: .status.version
        - name: Health
          type: string
          jsonPath: .status.health
        - name: Nodes
          type: integer
          jsonPath: .status.nodes
        - name: Phase
          type: string
          jsonPath: .status.phase
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [diskSize]
              properties:
                image:
                  type: string
                  description: OpenSearch image (e.g., opensearchproject/opensearch:<tag>)
                  default: opensearchproject/opensearch:3.2.0
                replicas:
                  type: integer
                  minimum: 3
                  default: 3
                diskSize:
                  type: string
                resources:
                  description: |-
                    Regular Kubernetes resource requests and limits for OpenSearch nodes.
                  properties:
                    limits:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    requests:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                  type: object
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                tolerations:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      value:
                        type: string
                      effect:
                        type: string
            status:
              type: object
              properties:
                health:
                  type: string
                nodes:
                  type: integer
                version:
                  type: string
                phase:
                  type: string
