apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reclaim-the-stack-opensearch
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: opensearch-operator
      app.kubernetes.io/name: opensearch
  endpoints:
    - port: http
      scheme: http
      path: /_prometheus/metrics
      interval: 30s
      scrapeTimeout: 10s
      basicAuth:
        username:
          name: opensearch-servicemonitor-basic-auth
          key: username
        password:
          name: opensearch-servicemonitor-basic-auth
          key: password
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: opensearch-servicemonitor-basic-auth
  namespace: monitoring
stringData:
  username: metrics
  password: <the-password-found-in-opensearch-operator/opensearch-metrics-basic-auth-secret>
