apiVersion: opensearch.reclaim-the-stack.com/v1alpha1
kind: OpenSearch
metadata:
  name: simple
  namespace: default
spec:
  replicas: 3
  diskSize: 5Gi
  resources:
    requests:
      memory: 4Gi
    limits:
      memory: 4Gi
