apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: %{name}
  namespace: %{namespace}
  labels:
    app.kubernetes.io/name: %{name}
  ownerReferences: %{owner_references}
spec:
  serviceName: %{name}
  replicas: %{replicas}
  selector:
    matchLabels:
      app.kubernetes.io/name: %{name}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: %{name}
    spec:
      nodeSelector: %{node_selector}
      tolerations: %{tolerations}
      containers:
        - name: opensearch
          image: %{image}
          ports:
            - name: "http"
              containerPort: 9200
          env: [
            # MVP runs single-node; remove this once you add real clustering logic
            { name: "discovery.type", value: "single-node" },
            { name: "OPENSEARCH_JAVA_OPTS", value: "-Xms512m -Xmx512m" },
            { name: "DISABLE_SECURITY_PLUGIN", value: "true" },
          ]
          volumeMounts:
            - name: "data"
              mountPath: "/usr/share/opensearch/data"
          readinessProbe:
            httpGet: { path: "/_cluster/health", port: 9200 }
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          resources: %{resources}
  volumeClaimTemplates:
    - metadata:
        name: "data"
      spec:
        accessModes: [ReadWriteOnce]
        resources: { requests: { storage: %{disk_size} } }
